name: evencir_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # state management
  provider: ^6.1.5

  # network
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  # animation
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.12



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
